# -*- coding: utf-8 -*-
"""Modulo4_EDA_Vendas_Professor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKfYkRmZLh4WR08h4gdvaii5TaVJYA53

# **Análise Exploratória de Dados com NumPy e Pandas**
### Versão do Professor (com respostas)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (7,4)
plt.rcParams['font.size'] = 11

df = pd.read_csv("https://raw.githubusercontent.com/fisicorj/aulacienciadedados/refs/heads/main/vendas_supermercado_BR.csv")
df.head()

"""## 1. Estatísticas Descritivas"""

print("Média:", df['preco_unitario'].mean())
print("Mediana:", df['preco_unitario'].median())
print("Desvio Padrão:", df['preco_unitario'].std())

"""## 2. Valores Ausentes"""

df.isna().sum()

"""## 3. Outliers (Z-score)"""

df['z'] = (df['preco_unitario'] - df['preco_unitario'].mean()) / df['preco_unitario'].std()
df[df['z'].abs() > 2]

"""## 4. Gráficos"""

df.groupby('produto')['preco_unitario'].mean().plot(kind='bar')
plt.show()

plt.scatter(df['preco_unitario'], df['quantidade'])
plt.show()

"""## 5. Exemplos de Insights

- Preços de hortifruti variam mais do que mercearia.
- Itens de maior preço têm menor quantidade comprada.
- Categorias têm comportamento de venda distinto ao longo do tempo.
"""